export default {
    ladybug: {
        movementPattern: [
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, 2],
            [1, -2],
            [1, 2],
            [2, -1],
            [2, 1]
        ],
        attackPattern: [
            [-1, -1],
            [-1, 0],
            [-1, 1],
            [0, -1],
            [0, 1],
            [1, -1],
            [1, 0],
            [1, 1],
        ],
        movementCost: 4,
        attackCost: 4
    },
    mosquito: {
        movementPattern: [
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, 2],
            [1, -2],
            [1, 2],
            [2, -1],
            [2, 1]
        ],
        attackPattern: [
            [-2, 0],
            [-1, 0],
            [0, -2],
            [0, -1],
            [0, 1],
            [0, 2],
            [1, 0],
            [2, 0],
        ],
        movementCost: 4,
        attackCost: 4
    },
    spider: {
        movementPattern: [
            [-2, -2],
            [-2, 2],
            [-1, -1],
            [-1, 1],
            [1, -1],
            [1, 1],
            [2, -2],
            [2, 2],
        ],
        attackPattern: [
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, 2],
            [1, -2],
            [1, 2],
            [2, 1],
            [2, -1],
        ],
        movementCost: 4,
        attackCost: 4
    },
    mantis: {
        movementPattern: [
            [-3, -3],
            [-3, 0],
            [-3, 3],
            [-2, -2],
            [-2, -1],
            [-2, 0],
            [-2, 1],
            [-2, 2],
            [-1, -2],
            [-1, 2],
            [0, -3],
            [0, -2],
            [0, 2],
            [0, 3],
            [1, -2],
            [1, 2],
            [2, -2],
            [2, -1],
            [2, 0],
            [2, 1],
            [2, 2],
            [3, -3],
            [3, 0],
            [3, 3],
        ],
        attackPattern: [
            [-3, -2],
            [-3, 2],
            [-2, -3],
            [-2, 3],
            [-1, -1],
            [-1, 0],
            [-1, 1],
            [0, -1],
            [0, 1],
            [1, -1],
            [1, 0],
            [1, 1],
            [3, -2],
            [3, 2],
            [2, -3],
            [2, 3],
        ],
        movementCost: 4,
        attackCost: 4
    },
    dragonfly: {
        movementPattern: [
            [-3, -1],
            [-3, 0],
            [-3, 1],
            [-2, -2],
            [-2, 0],
            [-2, 2],
            [-1, -3],
            [-1, 0],
            [-1, 3],
            [0, -3],
            [0, -2],
            [0, -1],
            [0, 1],
            [0, 2],
            [0, 3],
            [1, -3],
            [1, 0],
            [1, 3],
            [2, -2],
            [2, 0],
            [2, 2],
            [3, -1],
            [3, 0],
            [3, 1],
        ],
        attackPattern: [
            [-3, -3],
            [-3, 3],
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, -1],
            [-1, 1],
            [-1, 2],
            [1, -2],
            [1, -1],
            [1, 1],
            [1, 2],
            [2, -1],
            [2, 1],
            [3, -3],
            [3, 3],
        ],
        movementCost: 4,
        attackCost: 4
    },
    grub: {
        movementPattern: [
            [-1, 0],
            [0, -1],
            [0, 1],
            [1, 0],
        ],
        //TODO: attqck pattern
        attackPattern: [],
        movementCost: 1,
        attackCost: 0,
    },
    ant: {
        movementPattern: [
            [-2, -1],
            [-2, 1],
            [-1, 0],
            [0, -1],
            [0, 1],
            [1, 0],
            [2, 1],
            [2, -1],
        ],
        //TODO: attqck pattern
        attackPattern: [],
        movementCost: 1,
        attackCost: 1
    },
    inchworm: {
        movementPattern: [
            [-1, 0],
            [-2, 0],
            [0, -1],
            [0, -2],
            [0, 1],
            [0, 2],
            [1, 0],
            [2, 0],
        ],
        //TODO: attqck pattern
        attackPattern: [],
        movementCost: 1,
        attackCost: 1
    },
}