export default {
    ladybug: {
        movementPattern: [
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, 2],
            [1, -2],
            [1, 2],
            [2, -1],
            [2, 1]
        ],
        attackPattern: [
            [-1, -1],
            [-1, 0],
            [-1, 1],
            [0, -1],
            [0, 1],
            [1, -1],
            [1, 0],
            [1, 1],
        ],
    },
    mosquito: {
        movementPattern: [
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, 2],
            [1, -2],
            [1, 2],
            [2, -1],
            [2, 1]
        ],
        attackPattern: [
            [-2, 0],
            [-1, 0],
            [0, -2],
            [0, -1],
            [0, 1],
            [0, 2],
            [1, 0],
            [2, 0],
        ],
    },
    spider: {
        movementPattern: [
            [-2, -2],
            [-2, 2],
            [-1, -1],
            [-1, 1],
            [1, -1],
            [1, 1],
            [2, -2],
            [2, 2],
        ],
        attackPattern: [
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, 2],
            [1, -2],
            [1, 2],
            [2, 1],
            [2, -1],
        ],
    },
    mantis: {
        movementPattern: [
            [-3, -3],
            [-3, 0],
            [-3, 3],
            [-2, -2],
            [-2, -1],
            [-2, 0],
            [-2, 1],
            [-2, 2],
            [-1, -2],
            [-1, 2],
            [0, -3],
            [0, -2],
            [0, 2],
            [0, 3],
            [1, -2],
            [1, 2],
            [2, -2],
            [2, -1],
            [2, 0],
            [2, 1],
            [2, 2],
            [3, -3],
            [3, 0],
            [3, 3],
        ],
        attackPattern: [
            [-3, -2],
            [-3, 2],
            [-2, -3],
            [-2, 3],
            [-1, -1],
            [-1, 0],
            [-1, 1],
            [0, -1],
            [0, 1],
            [1, -1],
            [1, 0],
            [1, 1],
            [3, -2],
            [3, 2],
            [2, -3],
            [2, 3],
        ],
    },
    dragonfly: {
        movementPattern: [
            [-3, -1],
            [-3, 0],
            [-3, 1],
            [-2, -2],
            [-2, 0],
            [-2, 2],
            [-1, -3],
            [-1, 0],
            [-1, 3],
            [0, -3],
            [0, -2],
            [0, -1],
            [0, 1],
            [0, 2],
            [0, 3],
            [1, -3],
            [1, 0],
            [1, 3],
            [2, -2],
            [2, 0],
            [2, 2],
            [3, -1],
            [3, 0],
            [3, 1],
        ],
        attackPattern: [
            [-3, -3],
            [-3, 3],
            [-2, -1],
            [-2, 1],
            [-1, -2],
            [-1, -1],
            [-1, 1],
            [-1, 2],
            [1, -2],
            [1, -1],
            [1, 1],
            [1, 2],
            [2, -1],
            [2, 1],
            [3, -3],
            [3, 3],
        ],
    },
    grub: {
        movementPattern: [
            [-1, 0],
            [0, -1],
            [0, 1],
            [1, 0],
        ],
        attackPattern: [
            [-1,-1],
            [-1,1],
            [1,-1],
            [1,1]
        ],
    },
    ant: {
        movementPattern: [
            [-2, -1],
            [-2, 1],
            [-1, 0],
            [0, -1],
            [0, 1],
            [1, 0],
            [2, 1],
            [2, -1],
        ],
        //TODO: attqck pattern
        attackPattern: [],
    },
    inchworm: {
        movementPattern: [
            [-1, 0],
            [0, -1],
            [0, 1],
            [1, 0],
        ],
        attackPattern: [
            [-1,-1],
            [-1,1],
            [1,-1],
            [1,1]
        ],
    },
}

export const boardSetup = [
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "dragonfly", null, "grub", null, null, null, null, null, "inchworm", null, "dragonfly", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "ant", null, "grub", null, null, null, null, null, "inchworm", null, "ant", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "ladybug", null, "grub", null, null, null, null, null, "inchworm", null, "mosquito", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "spider", null, "grub", null, null, null, null, null, "inchworm", null, "mantis", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "spider", null, "grub", null, null, null, null, null, "inchworm", null, "mantis", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "ladybug", null, "grub", null, null, null, null, null, "inchworm", null, "mosquito", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "ant", null, "grub", null, null, null, null, null, "inchworm", null, "ant", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "dragonfly", null, "grub", null, null, null, null, null, "inchworm", null, "dragonfly", null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null],
]